#include "laic/gguf.hpp"
#include "laic/half.hpp"
#include <algorithm>
#include <cstring>
#include <fstream>
#include <limits>
#include <stdexcept>
namespace laic { namespace {
class Reader{const uint8_t*p_;const uint8_t*e_;public:Reader(const uint8_t*p,size_t n):p_(p),e_(p+n){}void need(size_t n){if(n>size_t(e_-p_))throw std::runtime_error("invalid/truncated GGUF");}uint8_t u8(){need(1);return*p_++;}int8_t i8(){return int8_t(u8());}uint16_t u16(){need(2);uint16_t v=p_[0]|(uint16_t(p_[1])<<8);p_+=2;return v;}int16_t i16(){return int16_t(u16());}uint32_t u32(){need(4);uint32_t v=uint32_t(p_[0])|(uint32_t(p_[1])<<8)|(uint32_t(p_[2])<<16)|(uint32_t(p_[3])<<24);p_+=4;return v;}int32_t i32(){return int32_t(u32());}uint64_t u64(){need(8);uint64_t v=0;for(int i=0;i<8;++i)v|=uint64_t(p_[i])<<(8*i);p_+=8;return v;}int64_t i64(){return int64_t(u64());}float f32(){uint32_t x=u32();float v;std::memcpy(&v,&x,4);return v;}double f64(){uint64_t x=u64();double v;std::memcpy(&v,&x,8);return v;}bool b(){return u8()!=0;}std::string str(){uint64_t n=u64();if(n>uint64_t(e_-p_))throw std::runtime_error("invalid GGUF string");std::string s(reinterpret_cast<const char*>(p_),size_t(n));p_+=n;return s;}size_t pos(const uint8_t*base)const{return size_t(p_-base);}};
GgufValue value(Reader&r,uint32_t t){switch(t){case 0:return uint64_t(r.u8());case 1:return int64_t(r.i8());case 2:return uint64_t(r.u16());case 3:return int64_t(r.i16());case 4:return uint64_t(r.u32());case 5:return int64_t(r.i32());case 6:return double(r.f32());case 7:return r.b();case 8:return r.str();case 10:return r.u64();case 11:return r.i64();case 12:return r.f64();case 9:{uint32_t et=r.u32();uint64_t n=r.u64();if(n>100000000ULL)throw std::runtime_error("GGUF array too large");if(et==8){std::vector<std::string>a;a.reserve(size_t(n));for(uint64_t i=0;i<n;++i)a.push_back(r.str());return a;}std::vector<uint64_t>a;a.reserve(size_t(n));for(uint64_t i=0;i<n;++i){GgufValue v=value(r,et);if(auto p=std::get_if<uint64_t>(&v))a.push_back(*p);else if(auto q=std::get_if<int64_t>(&v))a.push_back(uint64_t(*q));else throw std::runtime_error("unsupported GGUF array type");}return a;}default:throw std::runtime_error("unsupported GGUF metadata type");}}
size_t block_size(GgmlType t){switch(t){case GgmlType::F32:return 4;case GgmlType::F16:return 2;case GgmlType::Q4_0:return 18;case GgmlType::Q4_1:return 20;case GgmlType::Q5_0:return 22;case GgmlType::Q5_1:return 24;case GgmlType::Q8_0:return 34;case GgmlType::Q2_K:return 84;case GgmlType::Q3_K:return 110;case GgmlType::Q4_K:return 144;case GgmlType::Q5_K:return 176;case GgmlType::Q6_K:return 210;}throw std::runtime_error("unsupported GGML type");}
float h(const uint8_t*p){return Half::from_bits(uint16_t(p[0])|(uint16_t(p[1])<<8)).to_float();}
}}
namespace laic {
size_t GgufTensor::elements()const noexcept{size_t n=1;for(auto d:shape){if(d>std::numeric_limits<size_t>::max()/n)return 0;n*=size_t(d);}return n;}
size_t GgufTensor::bytes()const noexcept{size_t n=elements();if(type==GgmlType::F32)return n*4;if(type==GgmlType::F16)return n*2;return (n+31)/32*block_size(type);}
float GgufTensor::value(size_t i)const{if(!data||i>=elements())throw std::out_of_range("GGUF tensor index");if(type==GgmlType::F32){float v;std::memcpy(&v,data+i*4,4);return v;}if(type==GgmlType::F16)return h(data+i*2);size_t b=i/32,o=i%32;const uint8_t*q=data+b*block_size(type);if(type==GgmlType::Q8_0)return h(q)*float(int8_t(q[2+o]));if(type==GgmlType::Q4_0){uint8_t z=q[2+o/2];return h(q)*float((o&1)?(z>>4):(z&15)-8);}if(type==GgmlType::Q4_1){uint8_t z=q[4+o/2];return h(q)*float((o&1)?(z>>4):(z&15))+h(q+2);}if(type==GgmlType::Q5_0){uint32_t qh;std::memcpy(&qh,q+2,4);uint8_t z=q[6+o/2];int v=(o&1)?(z>>4):(z&15);v|=((qh>>o)&1)<<4;return h(q)*float(v-16);}if(type==GgmlType::Q5_1){uint32_t qh;std::memcpy(&qh,q+4,4);uint8_t z=q[8+o/2];int v=(o&1)?(z>>4):(z&15);v|=((qh>>o)&1)<<4;return h(q)*float(v)+h(q+2);}size_t sb=i/256,p=i%256,sub=p/128,pl=p%128,g=pl/32,e=pl%32;if(type==GgmlType::Q2_K){const uint8_t*B=data+sb*84;uint8_t sc=B[g+sub*8];float d=h(B+80),mn=h(B+82);int qv=(B[16+sub*32+e]>>(g*2))&3;return d*float(sc&15)*qv-mn*float(sc>>4);}if(type==GgmlType::Q3_K){const uint8_t*B=data+sb*110;uint32_t s0,s1,s2;std::memcpy(&s0,B+96,4);std::memcpy(&s1,B+100,4);std::memcpy(&s2,B+104,4);uint32_t a[4]={(s0&0x0f0f0f0f)|((s2&0x03030303)<<4),(s1&0x0f0f0f0f)|(((s2>>2)&0x03030303)<<4),((s0>>4)&0x0f0f0f0f)|(((s2>>4)&0x03030303)<<4),((s1>>4)&0x0f0f0f0f)|(((s2>>6)&0x03030303)<<4)};int si=sub*8+g*2+(e>=16);float d=h(B+108)*float(int8_t((a[si/4]>>(8*(si%4)))&255)-32);int qv=(B[32+sub*32+e]>>(g*2))&3;int sv=qv-((B[e]&(1<<(sub*4+g)))?0:4);return d*sv;}if(type==GgmlType::Q4_K||type==GgmlType::Q5_K){const size_t bs=type==GgmlType::Q4_K?144:176;const uint8_t*B=data+sb*bs;size_t grp=p/64,hal=(p%64)/32,ee=p%32,si=grp*2+hal;uint8_t sc[8],sm[8];for(int z=0;z<8;++z){sc[z]=(z<4)?B[4+z]&63:(B[8+z]&0xF)|((B[4+z-4]>>6)<<4);sm[z]=(z<4)?B[8+z]&63:(B[8+z]>>4)|((B[4+z-4]>>6)<<4);}float d=h(B),mn=h(B+2);int qv=hal?(B[16+ee]>>4):(B[16+ee]&15);int high=0;if(type==GgmlType::Q5_K)high=(B[16+32+ee]&(1<<(grp*2+hal)))?16:0;return d*sc[si]*float(qv+high)-mn*sm[si];}if(type==GgmlType::Q6_K){const uint8_t*B=data+sb*210;size_t grp=(p%128)/32,local=p%32;int qb=(grp&1)?(B[32+local]>>4):(B[local]&15);int hb=(B[128+local]>>(grp*2))&3;int scidx=grp*2+local/16;int8_t sc=int8_t(B[192+sub*8+scidx]);return h(B+208)*float(sc)*float((qb|(hb<<4))-32);}throw std::runtime_error("unsupported GGUF tensor type");}
void GgufModel::load(const std::string&path){std::ifstream f(path,std::ios::binary|std::ios::ate);if(!f)throw std::runtime_error("cannot open GGUF: "+path);auto sz=f.tellg();if(sz<0)throw std::runtime_error("cannot size GGUF");file_.resize(size_t(sz));f.seekg(0);f.read(reinterpret_cast<char*>(file_.data()),std::streamsize(file_.size()));if(!f)throw std::runtime_error("cannot read GGUF");meta_.clear();tensors_.clear();path_=path;Reader r(file_.data(),file_.size());if(r.u32()!=0x46554747U)throw std::runtime_error("bad GGUF magic");uint32_t ver=r.u32();if(ver<2||ver>3)throw std::runtime_error("unsupported GGUF version");uint64_t nt=r.u64(),nm=r.u64();if(nt>1000000||nm>1000000)throw std::runtime_error("unreasonable GGUF counts");for(uint64_t i=0;i<nm;++i){std::string k=r.str();uint32_t t=r.u32();meta_.emplace(std::move(k),value(r,t));}struct Info{std::string name;std::vector<uint64_t>shape;GgmlType type;uint64_t off;};std::vector<Info>infos;infos.reserve(size_t(nt));for(uint64_t i=0;i<nt;++i){Info x;x.name=r.str();uint32_t nd=r.u32();if(nd>8)throw std::runtime_error("invalid GGUF rank");x.shape.resize(nd);for(auto&d:x.shape)d=r.u64();x.type=GgmlType(r.u32());x.off=r.u64();(void)block_size(x.type);infos.push_back(std::move(x));}uint64_t align=u64("general.alignment",32);if(!align||align>4096)align=32;size_t raw=r.pos(file_.data());size_t start=(raw+size_t(align)-1)/size_t(align)*size_t(align);if(start>file_.size())throw std::runtime_error("tensor data starts past end");for(auto&x:infos){if(x.off>uint64_t(file_.size()-start))throw std::runtime_error("tensor offset out of range");size_t base=start+size_t(x.off);GgufTensor t;t.name=x.name;t.shape=std::move(x.shape);t.type=x.type;t.offset=x.off;t.data=file_.data()+base;if(t.bytes()>file_.size()-base)throw std::runtime_error("tensor data out of range");tensors_.emplace(t.name,std::move(t));}}
const GgufTensor&GgufModel::tensor(const std::string&n)const{auto it=tensors_.find(n);if(it==tensors_.end())throw std::runtime_error("missing tensor: "+n);return it->second;}bool GgufModel::has_tensor(const std::string&n)const noexcept{return tensors_.find(n)!=tensors_.end();}const GgufValue*GgufModel::metadata(const std::string&k)const noexcept{auto it=meta_.find(k);return it==meta_.end()?nullptr:&it->second;}uint64_t GgufModel::u64(const std::string&k,uint64_t fb)const{auto v=metadata(k);if(!v)return fb;if(auto p=std::get_if<uint64_t>(v))return*p;if(auto p=std::get_if<int64_t>(v))return uint64_t(*p);if(auto p=std::get_if<bool>(v))return*p?1:0;return fb;}double GgufModel::f64(const std::string&k,double fb)const{auto v=metadata(k);if(!v)return fb;if(auto p=std::get_if<double>(v))return*p;if(auto p=std::get_if<uint64_t>(v))return double(*p);return fb;}std::string GgufModel::str(const std::string&k,const std::string&fb)const{auto v=metadata(k);if(!v)return fb;if(auto p=std::get_if<std::string>(v))return*p;return fb;}const std::vector<std::string>&GgufModel::strings(const std::string&k)const{auto v=metadata(k);if(!v)return empty_strings_;if(auto p=std::get_if<std::vector<std::string>>(v))return*p;return empty_strings_;}
}