#include "laic/inference.hpp"
#include "laic/compute_dot.hpp"
#include "laic/quant_v2.hpp"
#include "laic/prefetch.hpp"
#include <algorithm>
#include <atomic>
#include <condition_variable>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <limits>
#include <mutex>
#include <numeric>
#include <random>
#include <stdexcept>
#include <thread>
namespace laic { namespace {
class WorkerPool { std::vector<std::thread> workers_; std::mutex mu_; std::condition_variable cv_,done_; std::function<void(size_t)> fn_; std::atomic<size_t> next_{0}; size_t jobs_=0,active_=0,generation_=0; bool stop_=false; void worker(){size_t seen=0;for(;;){std::unique_lock<std::mutex>l(mu_);cv_.wait(l,[&]{return stop_||generation_!=seen;});if(stop_)return;seen=generation_;auto fn=fn_;size_t n=jobs_;l.unlock();for(;;){size_t i=next_.fetch_add(1,std::memory_order_relaxed);if(i>=n)break;fn(i);}l.lock();if(--active_==0)done_.notify_one();}} public: WorkerPool(){unsigned n=std::thread::hardware_concurrency();if(!n)n=1;workers_.reserve(n);for(unsigned i=0;i<n;i++)workers_.emplace_back(&WorkerPool::worker,this);} ~WorkerPool(){{std::lock_guard<std::mutex>l(mu_);stop_=true;cv_.notify_all();}for(auto&t:workers_)if(t.joinable())t.join();} size_t size()const noexcept{return workers_.size();} void run(size_t n,const std::function<void(size_t)>&f){if(!n)return;if(n<workers_.size()*2){for(size_t i=0;i<n;i++)f(i);return;}{std::lock_guard<std::mutex>l(mu_);jobs_=n;fn_=f;next_.store(0,std::memory_order_relaxed);active_=workers_.size();++generation_;}cv_.notify_all();std::unique_lock<std::mutex>l(mu_);done_.wait(l,[&]{return active_==0;});}};
static WorkerPool& pool(){static WorkerPool p;return p;}
static size_t scalar_bytes(GgmlType t){switch(t){case GgmlType::F32:return 4;case GgmlType::F16:return 2;default:return 0;}}
static float quant_dot(const GgufTensor&w,const float*x,size_t base,size_t n){float s=0.f;for(size_t i=0;i<n;i++)s+=quant_v2::value(w.type,w.data,base+i)*x[i];return s;}
static float dot_cached(const GgufTensor&w,const float*x,size_t base,size_t n,const CachePlan&cp,const std::atomic<bool>&stop){if(w.type==GgmlType::F16||w.type==GgmlType::F32){const size_t sb=scalar_bytes(w.type);size_t tile=cp.l1_tile_bytes/(sb?sb*2:8);if(!tile)tile=32;float s=0.f;for(size_t j=0;j<n;j+=tile){if(stop.load(std::memory_order_relaxed))return 0.f;size_t len=std::min(tile,n-j);const uint8_t*wp=w.data+(base+j)*sb;if(cp.cache_line_bytes)prefetch_range(wp,len*sb,cp.cache_line_bytes);s+=(w.type==GgmlType::F16?compute::dot_f16(wp,x+j,len):compute::dot_f32(wp,x+j,len));}return s;}return quant_dot(w,x,base,n);}
static float silu(float x){return x/(1.f+std::exp(-x));}
static void rmsnorm(std::vector<float>&x,const GgufTensor&w,float eps,const std::atomic<bool>&stop){float ss=0.f;for(float v:x)ss+=v*v;float inv=1.f/std::sqrt(ss/float(x.size())+eps);pool().run(x.size(),[&](size_t i){if(!stop.load(std::memory_order_relaxed))x[i]*=inv*w.value(i);});if(stop.load())throw std::runtime_error("generation stopped");}
static void rope(std::vector<float>&x,size_t heads,size_t hd,size_t rd,size_t pos,float theta){rd=std::min(rd,hd);for(size_t h=0;h<heads;h++)for(size_t i=0;i<rd;i+=2){float a=float(pos)*std::pow(theta,-float(i)/float(hd));float c=std::cos(a),s=std::sin(a);size_t b=h*hd+i;float u=x[b],v=x[b+1];x[b]=u*c-v*s;x[b+1]=u*s+v*c;}}
}
void LlamaRuntime::load(const std::string&path){stop_requested_.store(false,std::memory_order_relaxed);cache_plan_=CachePlan::detect();model_.load(path);if(model_.str("general.architecture","")!="llama")throw std::runtime_error("unsupported architecture: expected llama-family GGUF");hidden_=model_.u64("llama.embedding_length");layers_=model_.u64("llama.block_count");heads_=model_.u64("llama.attention.head_count");kv_heads_=model_.u64("llama.attention.head_count_kv",heads_);ffn_=model_.u64("llama.feed_forward_length");ctx_=model_.u64("llama.context_length",2048);rope_dim_=model_.u64("llama.rope.dimension_count",hidden_/std::max<size_t>(1,heads_));theta_=float(model_.f64("llama.rope.freq_base",10000));eps_=float(model_.f64("llama.attention.layer_norm_rms_epsilon",1e-5));if(!hidden_||!layers_||!heads_||!kv_heads_||hidden_%heads_||heads_%kv_heads_||!ffn_)throw std::runtime_error("invalid llama architecture metadata");head_dim_=hidden_/heads_;if(!rope_dim_||rope_dim_>head_dim_||(rope_dim_&1))throw std::runtime_error("invalid RoPE dimension");tokenizer_.load(model_);cache_.assign(layers_,{});size_t reserve=std::min(ctx_,size_t(256))*kv_heads_*head_dim_;for(auto&c:cache_){c.k.reserve(reserve);c.v.reserve(reserve);}pos_=0;if(!model_.has_tensor("token_embd.weight")||!model_.has_tensor("output_norm.weight"))throw std::runtime_error("missing required tensors");}
std::vector<float>LlamaRuntime::embedding(uint32_t id)const{const auto&w=model_.tensor("token_embd.weight");if(w.shape.size()!=2||w.shape[0]!=hidden_||id>=w.shape[1])throw std::runtime_error("invalid embedding tensor");std::vector<float>x(hidden_);for(size_t i=0;i<hidden_;i++)x[i]=(w.type==GgmlType::F16||w.type==GgmlType::F32)?w.value(id*hidden_+i):quant_v2::value(w.type,w.data,id*hidden_+i);return x;}
std::vector<float>LlamaRuntime::matvec(const GgufTensor&w,const std::vector<float>&x,size_t out,size_t in)const{if(w.shape.size()!=2||w.shape[0]!=in||w.shape[1]!=out)throw std::runtime_error("unexpected weight shape: "+w.name);std::vector<float>y(out);pool().run(out,[&](size_t o){if(stop_requested_.load(std::memory_order_relaxed))return;y[o]=dot_cached(w,x.data(),o*in,in,cache_plan_,stop_requested_);});if(stop_requested_.load())throw std::runtime_error("generation stopped");return y;}
void LlamaRuntime::norm(std::vector<float>&x,const GgufTensor&w)const{if(w.elements()!=x.size())throw std::runtime_error("invalid norm tensor: "+w.name);rmsnorm(x,w,eps_,stop_requested_);}
std::vector<float>LlamaRuntime::step(uint32_t token){if(pos_>=ctx_)throw std::runtime_error("context length exceeded");std::vector<float>x=embedding(token);for(size_t l=0;l<layers_;l++){if(stop_requested_.load())throw std::runtime_error("generation stopped");std::string p="blk."+std::to_string(l)+".";auto a=x;norm(a,model_.tensor(p+"attn_norm.weight"));auto q=matvec(model_.tensor(p+"attn_q.weight"),a,hidden_,hidden_);auto k=matvec(model_.tensor(p+"attn_k.weight"),a,kv_heads_*head_dim_,hidden_);auto v=matvec(model_.tensor(p+"attn_v.weight"),a,kv_heads_*head_dim_,hidden_);rope(q,heads_,head_dim_,rope_dim_,pos_,theta_);rope(k,kv_heads_,head_dim_,rope_dim_,pos_,theta_);auto&lc=cache_[l];size_t stride=kv_heads_*head_dim_;lc.k.insert(lc.k.end(),k.begin(),k.end());lc.v.insert(lc.v.end(),v.begin(),v.end());std::vector<float>attn(hidden_);size_t group=heads_/kv_heads_;pool().run(heads_,[&](size_t h){size_t kh=h/group;std::vector<float>scores(pos_+1);float mx=-std::numeric_limits<float>::infinity();for(size_t t=0;t<=pos_;t++){float s=0.f;for(size_t d=0;d<head_dim_;d++)s+=q[h*head_dim_+d]*lc.k[t*stride+kh*head_dim_+d];scores[t]=s/std::sqrt(float(head_dim_));mx=std::max(mx,scores[t]);}float den=0.f;for(float&s:scores){s=std::exp(s-mx);den+=s;}for(float&s:scores)s/=den;for(size_t d=0;d<head_dim_;d++){float z=0.f;for(size_t t=0;t<=pos_;t++)z+=scores[t]*lc.v[t*stride+kh*head_dim_+d];attn[h*head_dim_+d]=z;}});auto ao=matvec(model_.tensor(p+"attn_output.weight"),attn,hidden_,hidden_);compute::axpy_f32(x.data(),ao.data(),1.f,hidden_);auto f=x;norm(f,model_.tensor(p+"ffn_norm.weight"));auto gate=matvec(model_.tensor(p+"ffn_gate.weight"),f,ffn_,hidden_);auto up=matvec(model_.tensor(p+"ffn_up.weight"),f,ffn_,hidden_);pool().run(ffn_,[&](size_t i){gate[i]=silu(gate[i])*up[i];});auto down=matvec(model_.tensor(p+"ffn_down.weight"),gate,hidden_,ffn_);compute::axpy_f32(x.data(),down.data(),1.f,hidden_);}norm(x,model_.tensor("output_norm.weight"));const auto&out=model_.has_tensor("output.weight")?model_.tensor("output.weight"):model_.tensor("token_embd.weight");return matvec(out,x,tokenizer_.vocab_size(),hidden_);}
uint32_t LlamaRuntime::sample(const std::vector<float>&logits,const GenerationConfig&c,const std::vector<uint32_t>&history)const{std::vector<float>l=logits;if(c.repeat_penalty!=1.f)for(uint32_t id:history)if(id<l.size()){if(l[id]>=0)l[id]/=c.repeat_penalty;else l[id]*=c.repeat_penalty;}if(c.temperature<=0.f)return uint32_t(std::max_element(l.begin(),l.end())-l.begin());size_t k=c.top_k?std::min(c.top_k,l.size()):l.size();std::vector<size_t>ix(l.size());std::iota(ix.begin(),ix.end(),0);if(k<ix.size()){std::nth_element(ix.begin(),ix.begin()+k,ix.end(),[&](size_t a,size_t b){return l[a]>l[b];});ix.resize(k);}float mx=-std::numeric_limits<float>::infinity();for(size_t i:ix)mx=std::max(mx,l[i]);std::vector<double>p(k);double sum=0;for(size_t j=0;j<k;j++){p[j]=std::exp((l[ix[j]]-mx)/c.temperature);sum+=p[j];}for(double&v:p)v/=sum;if(c.top_p<1.f){std::vector<size_t>ord(k);std::iota(ord.begin(),ord.end(),0);std::sort(ord.begin(),ord.end(),[&](size_t a,size_t b){return p[a]>p[b];});double acc=0;size_t keep=0;for(size_t j:ord){acc+=p[j];keep++;if(acc>=c.top_p)break;}std::vector<size_t>nix;std::vector<double>np;for(size_t j:ord)if(nix.size()<keep){nix.push_back(ix[j]);np.push_back(p[j]);}double ns=0;for(double v:np)ns+=v;ix.swap(nix);p.swap(np);for(double&v:p)v/=ns;}std::mt19937_64 rng(c.seed?c.seed:std::random_device{}());std::discrete_distribution<size_t>d(p.begin(),p.end());return uint32_t(ix[d(rng)]);}
std::vector<uint32_t>LlamaRuntime::generate_ids(const std::string&prompt,const GenerationConfig&cfg){std::vector<uint32_t>out;generate_ids(prompt,cfg,[&](uint32_t id){out.push_back(id);return true;});return out;}
std::vector<uint32_t>LlamaRuntime::generate_ids(const std::string&prompt,const GenerationConfig&cfg,const TokenCallback&cb){stop_requested_.store(false,std::memory_order_relaxed);cache_.assign(layers_,{});size_t reserve=std::min(ctx_,size_t(256))*kv_heads_*head_dim_;for(auto&c:cache_){c.k.reserve(reserve);c.v.reserve(reserve);}pos_=0;std::string input=prompt;std::string templ=model_.str("tokenizer.chat_template","");if(templ.find("<|im_start|>")!=std::string::npos&&input.find("<|im_start|>")==std::string::npos)input="<|im_start|>user\n"+input+"<|im_end|>\n<|im_start|>assistant\n";auto ids=tokenizer_.encode(input);if(ids.empty())throw std::runtime_error("tokenization produced no tokens");if(tokenizer_.add_bos()&&ids.front()!=tokenizer_.bos_id())ids.insert(ids.begin(),tokenizer_.bos_id());std::vector<uint32_t>history=ids;std::vector<float>logits;for(uint32_t id:ids){logits=step(id);++pos_;}std::vector<uint32_t>generated;generated.reserve(cfg.max_tokens);for(size_t n=0;n<cfg.max_tokens;n++){if(stop_requested_.load())break;uint32_t next=sample(logits,cfg,history);if(next==tokenizer_.eos_id())break;history.push_back(next);generated.push_back(next);if(cb&&!cb(next))break;logits=step(next);++pos_;}return generated;}
std::string LlamaRuntime::generate(const std::string&prompt,const GenerationConfig&cfg){std::string out;generate_ids(prompt,cfg,[&](uint32_t id){out+=tokenizer_.decode(id);return true;});return out;}
}
