#include "laic/inference.hpp"
#include "laic/prefetch.hpp"
#include <algorithm>
#include <condition_variable>
#include <cmath>
#include <cstring>
#include <limits>
#include <mutex>
#include <numeric>
#include <random>
#include <stdexcept>
#include <thread>
namespace laic { namespace {
static inline float hf(uint16_t h){uint32_t s=h>>15,e=(h>>10)&31,f=h&1023;if(!e)return(s?-1.f:1.f)*std::ldexp(float(f),-24);if(e==31)return f?NAN:(s?-INFINITY:INFINITY);return(s?-1.f:1.f)*std::ldexp(1.f+float(f)/1024.f,int(e)-15);}
static inline uint16_t u16(const uint8_t*p){return uint16_t(p[0])|(uint16_t(p[1])<<8);}
static inline float elem(const GgufTensor&w,size_t i){const uint8_t*d=w.data;if(w.type==GgmlType::F32){float x;std::memcpy(&x,d+i*4,4);return x;}if(w.type==GgmlType::F16)return hf(u16(d+i*2));
size_t b=i/32,o=i%32; if(w.type==GgmlType::Q8_0){const uint8_t*q=d+b*34;return hf(u16(q))*float(int8_t(q[2+o]));}
if(w.type==GgmlType::Q4_0){const uint8_t*q=d+b*18;uint8_t z=q[2+o/2];return hf(u16(q))*float((o&1)?(z>>4):(z&15)-8);}
if(w.type==GgmlType::Q4_1){const uint8_t*q=d+b*20;uint8_t z=q[4+o/2];return hf(u16(q))*float((o&1)?(z>>4):(z&15))+hf(u16(q+2));}
if(w.type==GgmlType::Q5_0){const uint8_t*q=d+b*22;uint32_t qh;std::memcpy(&qh,q+2,4);uint8_t z=q[6+o/2];int v=(o&1)?z>>4:z&15;v|=((qh>>o)&1)<<4;return hf(u16(q))*float(v-16);}
if(w.type==GgmlType::Q5_1){const uint8_t*q=d+b*24;uint32_t qh;std::memcpy(&qh,q+4,4);uint8_t z=q[8+o/2];int v=(o&1)?z>>4:z&15;v|=((qh>>o)&1)<<4;return hf(u16(q))*float(v)+hf(u16(q+2));}
size_t sb=i/256,p=i%256,sub=p/128,pl=p%128,g=pl/32,e=pl%32;
if(w.type==GgmlType::Q2_K){const uint8_t*B=d+sb*84;uint8_t sc=B[sub*8+g];int q=(B[16+sub*32+e]>>(g*2))&3;return hf(u16(B+80))*float(sc&15)*q-hf(u16(B+82))*float(sc>>4);}
if(w.type==GgmlType::Q3_K){const uint8_t*B=d+sb*110;uint32_t s0,s1,s2;std::memcpy(&s0,B+96,4);std::memcpy(&s1,B+100,4);std::memcpy(&s2,B+104,4);uint32_t a[4]={(s0&0x0f0f0f0f)|((s2&0x03030303)<<4),(s1&0x0f0f0f0f)|(((s2>>2)&0x03030303)<<4),((s0>>4)&0x0f0f0f0f)|(((s2>>4)&0x03030303)<<4),((s1>>4)&0x0f0f0f0f)|(((s2>>6)&0x03030303)<<4)};int si=sub*8+g*2+(e>=16);int8_t sc=int8_t((a[si/4]>>(8*(si%4)))&255);int q=(B[32+sub*32+e]>>(g*2))&3;int sv=q-((B[e]&(1<<(sub*4+g)))?0:4);return hf(u16(B+108))*float(sc-32)*float(sv);}
if(w.type==GgmlType::Q4_K||w.type==GgmlType::Q5_K){const uint8_t*B=d+sb*(w.type==GgmlType::Q4_K?144:176);size_t grp=p/64,hal=(p%64)/32,ee=p%32,si=grp*2+hal;const uint8_t*sc=B+4;uint8_t scl=(si<4)?sc[si]&63:(sc[si+4]&15)|((sc[si-4]>>6)<<4);uint8_t sm=(si<4)?sc[si+4]&63:(sc[si+4]>>4)|((sc[si]>>6)<<4);int q=hal?(B[16+ee]>>4):(B[16+ee]&15);if(w.type==GgmlType::Q5_K&& (B[16+32+ee]&(1<<(grp*2+hal))))q+=16;return hf(u16(B))*float(scl*q)-hf(u16(B+2))*float(sm);}
if(w.type==GgmlType::Q6_K){const uint8_t*B=d+sb*210;size_t grp=(p%128)/32,local=p%32;int q=(grp&1)?B[32+local]>>4:B[local]&15;int h=(B[128+local]>>(grp*2))&3;int scidx=grp*2+local/16;return hf(u16(B+208))*float(int8_t(B[192+sub*8+scidx]))*float((q|(h<<4))-32);}
throw std::runtime_error("unsupported GGML tensor type");}

class Workers{std::vector<std::thread>w_;std::mutex m_;std::condition_variable cv_,done_;std::function<void(size_t)>fn_;size_t jobs_=0,active_=0,gen_=0;bool stop_=false;void worker(){size_t seen=0;for(;;){std::unique_lock<std::mutex>l(m_);cv_.wait(l,[&]{return stop_||gen_!=seen;});if(stop_)return;seen=gen_;auto f=fn_;size_t n=jobs_;l.unlock();for(;;){size_t i=next_.fetch_add(1,std::memory_order_relaxed);if(i>=n)break;f(i);}l.lock();if(--active_==0)done_.notify_one();}}std::atomic<size_t>next_{0};public:Workers(){unsigned n=std::thread::hardware_concurrency();if(!n)n=1;w_.reserve(n);for(unsigned i=0;i<n;i++)w_.emplace_back(&Workers::worker,this);}~Workers(){{std::lock_guard<std::mutex>l(m_);stop_=true;cv_.notify_all();}for(auto&t:w_)if(t.joinable())t.join();}void run(size_t n,const std::function<void(size_t)>&f){if(!n)return;if(n<w_.size()*2){for(size_t i=0;i<n;i++)f(i);return;}std::lock_guard<std::mutex>g(m_);jobs_=n;fn_=f;next_.store(0);active_=w_.size();++gen_;cv_.notify_all();std::unique_lock<std::mutex>l(m_);done_.wait(l,[&]{return active_==0;});}};
static Workers&workers(){static Workers x;return x;}
static inline float dot(const GgufTensor&w,const std::vector<float>&x,size_t base,size_t n,const CachePlan&cp,const std::atomic<bool>&stop){float s=0;size_t tk=cp.l1_tile_bytes?std::max<size_t>(4,cp.l1_tile_bytes/(sizeof(float)*2)):64;for(size_t j=0;j<n;j+=tk){if(stop.load(std::memory_order_relaxed))return 0;size_t len=std::min(tk,n-j);const uint8_t*wp=nullptr;if(w.type==GgmlType::F32)wp=w.data+(base+j)*4;else if(w.type==GgmlType::F16)wp=w.data+(base+j)*2;else wp=w.data+((base+j)/32)*(w.type==GgmlType::Q2_K?84:w.type==GgmlType::Q3_K?110:w.type==GgmlType::Q4_K?144:w.type==GgmlType::Q5_K?176:w.type==GgmlType::Q6_K?210:34);if(j+len<n)prefetch_range(wp,std::min<size_t>(len*(w.type==GgmlType::F32?4:2),cp.l2_window_bytes?cp.l2_window_bytes:len*2),cp.cache_line_bytes);for(size_t i=0;i<len;i++)s+=elem(w,base+j+i)*x[j+i];}return s;}
}
void LlamaRuntime::load(const std::string&path){stop_requested_.store(false);cache_plan_=CachePlan::detect();model_.load(path);if(model_.str("general.architecture","")!="llama")throw std::runtime_error("unsupported architecture: expected llama");hidden_=model_.u64("llama.embedding_length");layers_=model_.u64("llama.block_count");heads_=model_.u64("llama.attention.head_count");kv_heads_=model_.u64("llama.attention.head_count_kv",heads_);ffn_=model_.u64("llama.feed_forward_length");ctx_=model_.u64("llama.context_length",2048);rope_dim_=model_.u64("llama.rope.dimension_count",hidden_/heads_);theta_=float(model_.f64("llama.rope.freq_base",10000));eps_=float(model_.f64("llama.attention.layer_norm_rms_epsilon",1e-5));if(!hidden_||!layers_||!heads_||!kv_heads_||hidden_%heads_||heads_%kv_heads_)throw std::runtime_error("invalid llama dimensions");head_dim_=hidden_/heads_;tokenizer_.load(model_);cache_.assign(layers_,{});size_t reserve=std::min<size_t>(ctx_,256)*kv_heads_*head_dim_;for(auto&c:cache_){c.k.reserve(reserve);c.v.reserve(reserve);}pos_=0;if(!model_.has_tensor("token_embd.weight")||!model_.has_tensor("output_norm.weight"))throw std::runtime_error("missing required tensors");}
std::vector<float>LlamaRuntime::embedding(uint32_t id)const{const auto&w=model_.tensor("token_embd.weight");if(w.shape.size()!=2||id>=w.shape[1]||w.shape[0]!=hidden_)throw std::runtime_error("invalid embedding tensor");std::vector<float>x(hidden_);for(size_t i=0;i<hidden_;i++)x[i]=w.value(id*hidden_+i);return x;}
std::vector<float>LlamaRuntime::matvec(const GgufTensor&w,const std::vector<float>&x,size_t out,size_t in)const{if(w.shape.size()!=2||w.shape[0]!=in||w.shape[1]!=out)throw std::runtime_error("unexpected weight shape: "+w.name);std::vector<float>y(out);workers().run(out,[&](size_t o){if(stop_requested_.load(std::memory_order_relaxed))return;y[o]=dot(w,x,o*in,in,cache_plan_,stop_requested_);});if(stop_requested_.load(std::memory_order_relaxed))throw std::runtime_error("generation stopped");return y;}
void LlamaRuntime::norm(std::vector<float>&x,const GgufTensor&w)const{if(w.elements()!=x.size())throw std::runtime_error("invalid norm tensor: "+w.name);float ss=0;for(float v:x)ss+=v*v;float inv=1/std::sqrt(ss/float(x.size())+eps_);workers().run(x.size(),[&](size_t i){if(!stop_requested_.load())x[i]*=inv*w.value(i);});if(stop_requested_.load())throw std::runtime_error("generation stopped");}
static void rope(std::vector<float>&x,size_t heads,size_t hd,size_t rd,size_t pos,float theta){rd=std::min(rd,hd);for(size_t h=0;h<heads;h++)for(size_t i=0;i<rd;i+=2){float inv=std::pow(theta,-float(i)/float(hd)),a=float(pos)*inv,c=std::cos(a),s=std::sin(a);size_t b=h*hd+i,u=x[b],v=x[b+1];x[b]=u*c-v*s;x[b+1]=u*s+v*c;}}
static float silu(float x){return x/(1.f+std::exp(-x));}
std::vector<float>LlamaRuntime::step(uint32_t token){if(pos_>=ctx_)throw std::runtime_error("context length exceeded");std::vector<float>x=embedding(token);for(size_t l=0;l<layers_;l++){if(stop_requested_.load())throw std::runtime_error("generation stopped");std::string p="blk."+std::to_string(l)+".";auto a=x;norm(a,model_.tensor(p+"attn_norm.weight"));auto q=matvec(model_.tensor(p+"attn_q.weight"),a,hidden_,hidden_);auto k=matvec(model_.tensor(p+"attn_k.weight"),a,kv_heads_*head_dim_,hidden_);auto v=matvec(model_.tensor(p+"attn_v.weight"),a,kv_heads_*head_dim_,hidden_);rope(q,heads_,head_dim_,rope_dim_,pos_,theta_);rope(k,kv_heads_,head_dim_,rope_dim_,pos_,theta_);auto&lc=cache_[l];size_t stride=kv_heads_*head_dim_;lc.k.insert(lc.k.end(),k.begin(),k.end());lc.v.insert(lc.v.end(),v.begin(),v.end());std::vector<float>attn(hidden_);size_t group=heads_/kv_heads_;workers().run(heads_,[&](size_t h){size_t kh=h/group;std::vector<float>scores(pos_+1);float mx=-std::numeric_limits<float>::infinity();for(size_t t=0;t<=pos_;t++){float s=0;for(size_t d=0;d<head_dim_;d++)s+=q[h*head_dim_+d]*lc.k[t*stride+kh*head_dim_+d];scores[t]=s/std::sqrt(float(head_dim_));mx=std::max(mx,scores[t]);}float den=0;for(float&s:scores){s=std::exp(s-mx);den+=s;}for(float&s:scores)s/=den;for(size_t d=0;d<head_dim_;d++){float z=0;for(size_t t=0;t<=pos_;t++)z+=scores[t]*lc.v[t*stride+kh*head_dim_+d];attn[h*head_dim_+d]=z;}});auto ao=matvec(model_.tensor(p+"attn_output.weight"),attn,hidden_,hidden_);workers().run(hidden_,[&](size_t i){x[i]+=ao[i];});auto f=x;norm(f,model_.tensor(p+"ffn_norm.weight"));auto gate=matvec(model_.tensor(p+"ffn_gate.weight"),f,ffn_,hidden_);auto up=matvec(model_.tensor(p+"ffn_up.weight"),f,ffn_,hidden_);workers().run(ffn_,[&](size_t i){if(!stop_requested_.load())gate[i]=silu(gate[i])*up[i];});auto down=matvec(model_.tensor(p+"ffn_down.weight"),gate,hidden_,ffn_);workers().run(hidden_,[&](size_t i){x[i]+=down[i];});}norm(x,model_.tensor("output_norm.weight"));const auto&out=model_.has_tensor("output.weight")?model_.tensor("output.weight"):model_.tensor("token_embd.weight");return matvec(out,x,tokenizer_.vocab_size(),hidden_);}
uint32_t LlamaRuntime::sample(const std::vector<float>&logits,const GenerationConfig&c,const std::vector<uint32_t>&history)const{std::vector<float>l=logits;if(c.repeat_penalty!=1.f)for(uint32_t id:history)if(id<l.size()){if(l[id]>0)l[id]/=c.repeat_penalty;else l[id]*=c.repeat_penalty;}if(c.temperature<=0)return uint32_t(std::max_element(l.begin(),l.end())-l.begin());size_t k=c.top_k?std::min(c.top_k,l.size()):l.size();std::vector<size_t>ix(l.size());std::iota(ix.begin(),ix.end(),0);if(k<ix.size()){std::nth_element(ix.begin(),ix.begin()+k,ix.end(),[&](size_t a,size_t b){return l[a]>l[b];});ix.resize(k);}float mx=-std::numeric_limits<float>::infinity();for(auto i:ix)mx=std::max(mx,l[i]);std::vector<double>p(k);double sum=0;for(size_t j=0;j<k;j++){p[j]=std::exp((l[ix[j]]-mx)/c.temperature);sum+=p[j];}if(c.top_p<1.f){std::vector<size_t>ord(k);std::iota(ord.begin(),ord.end(),0);std::sort(ord.begin(),ord.end(),[&](size_t a,size_t b){return p[a]>p[b];});double cut=0;size_t keep=k;for(size_t n=0;n<k;n++){cut+=p[ord[n]]/sum;if(cut>=c.top_p){keep=n+1;break;}}std::vector<size_t>ni;ni.reserve(keep);for(size_t n=0;n<keep;n++)ni.push_back(ix[ord[n]]);ix.swap(ni);p.resize(keep);sum=0;mx=-std::numeric_limits<float>::infinity();for(auto id:ix)mx=std::max(mx,l[id]);for(size_t j=0;j<ix.size();j++){p[j]=std::exp((l[ix[j]]-mx)/c.temperature);sum+=p[j];}k=ix.size();}static thread_local std::mt19937_64 rng(std::random_device{}());if(c.seed)rng.seed(c.seed);double r=std::uniform_real_distribution<double>(0,sum)(rng);for(size_t j=0;j<k;j++)if((r-=p[j])<=0)return uint32_t(ix[j]);return uint32_t(ix.back());}
std::vector<uint32_t>LlamaRuntime::generate_ids(const std::string&prompt,const GenerationConfig&c){return generate_ids(prompt,c,{});}std::vector<uint32_t>LlamaRuntime::generate_ids(const std::string&prompt,const GenerationConfig&c,const TokenCallback&cb){stop_requested_.store(false);pos_=0;for(auto&v:cache_){v.k.clear();v.v.clear();}auto ids=tokenizer_.encode(prompt);if(ids.empty())ids.push_back(tokenizer_.bos_id());std::vector<uint32_t>history=ids,out;out.reserve(c.max_tokens);std::vector<float>logits;for(uint32_t id:ids){if(stop_requested_.load()||pos_>=ctx_)break;logits=step(id);++pos_;}for(size_t n=0;n<c.max_tokens&&pos_<ctx_;n++){if(stop_requested_.load())break;uint32_t next=sample(logits,c,history);out.push_back(next);history.push_back(next);if(cb&&!cb(next))break;if(next==tokenizer_.eos_id())break;logits=step(next);++pos_;}return out;}
std::string LlamaRuntime::generate(const std::string&prompt,const GenerationConfig&c){std::string out;for(uint32_t id:generate_ids(prompt,c))out+=tokenizer_.decode(id);return out;}
}